### PR TITLE
fix(v4) sign AWS requests only

### LINKED ISSUE #60: Unable to run lambda via lambci
I saw in https://github.com/Kong/kong-plugin-aws-lambda/issues/26 some work was done to allow local development but I cant seem to get this working.

The error I'm getting is;
```
 init.lua:286 [aws-lambda] /usr/local/share/lua/5.1/kong/plugins/aws-lambda/v4.lua:118: attempt to concatenate local 'region' (a nil value), client: 192.168.128.1, server: kong, request: "POST /lambda1 HTTP/1.1", host: "localhost:8000"
```

I'm testing with this kong.yml file (partial)
```
routes:
- name: lambda1
  paths: [ "/lambda1" ]

plugins:
- route: lambda1
  name: aws-lambda
  config:
    port: 9001
    host: host.docker.internal
    aws_key: abc
    aws_secret: abc
    function_name: order
```

And have `lambci` running locally and can invoke my local lambda like;
```
curl --location --request POST 'http://localhost:9001/2015-03-31/functions/order/invocations' \
--header 'Content-Type: application/json' \
--data-raw '{
    "path": "/api/order/13984e49-f798-40a3-a015-b798cdf9d157",
    "httpMethod": "GET"
}'
```
Another thing to note is that the local lambda service only runs on `http` and not `https` of which I dont see a setting to enable/force such a scheme.

### PR DESCRIPTION
**Pull request by locao**
Do not sign requests that are not for AWS Lambda, e.g. when using a CI server.

Fixes: #60

### CODE REVIEW

File: spec/plugins/aws-lambda/99-access_spec.lua [hunk 1]
```diff
@@ -352,6 +358,24 @@ for _, strategy in helpers.each_strategy() do
...
+          aws_secret           = "mock-secret",
+          function_name        = "functionWithMultiValueHeadersResponse",
+          host                 = "lambda18.test",
+          is_proxy_integration = true,
+        }
+      }
+
+      fixtures.dns_mock:A({
+        name = "lambda18.test",
+        address = "127.0.0.1",
```
Comment (Tieske) [inline spec/plugins/aws-lambda/99-access_spec.lua]:
```suggestion
        address = helpers.mock_upstream_host,
```

**Review by dndx — APPROVED** [review]
